### ISSUE TITLE
AttributeError: 'BartEncoder' object has no attribute 'main_input_name'

### ISSUE THREAD

**Issue by zeke-john** [siddharth-sharma7/fast-Bart#4]
Firstly, this repo has been very helpful and useful, so thank you, but whenever i run the model ([facebook/bart-large-cnn](https://huggingface.co/facebook/bart-large-cnn)) to try to summarize text, using the code below, i keep running into this error, and i'm honestly stuck, so any help would be greatly appreciated.

Code:

   

    from fastBart import export_and_get_onnx_model, OnnxBart, quantize
    from transformers import AutoTokenizer
    from pathlib import  Path
    from fastBart.ort_settings import get_onnx_runtime_sessions
    import os
    from fastBart.onnx_exporter import (
        generate_onnx_representation)

    model_name = 'facebook/bart-large-cnn'

    quant_model_paths = ['./models-bart/bart-large-cnn-encoder.onnx', './models-bart/bart-large-cnn-decoder.onnx', './models-bart/bart-large-cnn-init-decoder.onnx']
    model_sessions = get_onnx_runtime_sessions(tuple(quant_model_paths))

    quant_model_paths = tuple(quant_model_paths)

    model_sessions = get_onnx_runtime_sessions(quant_model_paths)
    model = OnnxBart(model_name, model_sessions)

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    input = """Since being shared on Reddit, the 21-second video has garnered more than 35,000 upvotes. People also filled the comment section with adorable comments.
    A Reddit user said that he liked the little cat staring at the mama dog for a moment. Another liked the calmness and patience of the mama dog.
    “This is soooo cute,” commented a third Reddit user. Many users also added that humans should learn kindness from these animals.
    Well, this is not the first time that a kitten was feeding on a nursing dog.Last year, a similar heartwarming video had surfaced 
    from a remote village in Nigeria that showed a little feline feeding on milk from a mama dog. The clip, which had gone viral, has 
    so far accumulated over 1 million views. Twitter users showered love for the dog and the little kitten. The 32-second clip was shared 
    by Reuters on its official Twitter handle with the caption, “It's a most unusual sight: a kitten was spotted feeding on milk from a nursing dog in a remote village in Nigeria.”
    """

    token = tokenizer(input, return_tensors='pt',  truncation=True)
    tokens = model.generate(input_ids=token['input_ids'],attention_mask=token['attention_mask'],num_beams=4)

    output = tokenizer.decode(tokens.squeeze(), skip_special_tokens=True)
    print(output)

Error:

    Traceback (most recent call last):
    File "/Users/zeke/Documents/Github/SumanyWeb/sumany/summarize/fast-Bart/bartoptimize.py", line 34, in <module>
        tokens = model.generate(input_ids=token['input_ids'],attention_mask=token['attention_mask'],num_beams=4)
    File "/usr/local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
        return func(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/transformers/generation_utils.py", line 1162, in generate
        inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(inputs, bos_token_id, model_kwargs)
    File "/usr/local/lib/python3.9/site-packages/transformers/generation_utils.py", line 412, in _prepare_model_inputs
        and self.encoder.main_input_name != self.main_input_name
    File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'BartEncoder' object has no attribute 'main_input_name'

**Comment by yilmazay74** [comment]
reducing the version for transformers to 4.10.0, it throws compilation errors.
It looks like transformers 4.10.0 is not compatible with rust which is needed to build wheels for tokenizers.
So the whole process gets stuck here.
Is not there any new version of fast bart that works without compilation and build problems?

**Comment by yilmazay74** [comment]
Here is the complete error log:

[complete error logs while installing transformers 4.10 for fast-bart.txt](https://github.com/user-attachments/files/20343878/complete.error.logs.while.installing.transformers.4.10.for.fast-bart.txt)

**Comment by yilmazay74** [comment]
Hi Zeke-john, 
Have you solved your problem? 
Unfortunately I could not make this fast-bart work. It would be great if someone in the fast bart developer group update the codes so that it can be used.
Unfortunately I could not find any other option which promises to speed up current BART models.
If someone has a direct or indirect solution I would really appreciate it.

Thanks in advance.
